#!/bin/bash
#
#  Install and set up required software
#

if [ -d bin/e00compr ]; then
    echo "E00CONV ALREADY SET UP"
else
  echo "SETTING UP E00CONV..."
  (
    mkdir -p bin && cd bin
    curl -OL http://avce00.maptools.org/dl/e00compr-1.0.1.tar.gz
    tar xzvf e00compr-1.0.1.tar.gz
    ln -s e00compr-1.0.1 e00compr
    cd e00compr-1.0.1
    make
  )
fi

if [ -f bin/imposm ]; then
    echo "IMPOSM ALREADY SET UP"
else
  echo "SETTING UP IMPOSM..."
  (
    mkdir -p bin && cd bin
    git clone https://github.com/omniscale/imposm3.git
    cd imposm3
    make build
    cd ..
    ln -s imposm3/imposm imposm
  )
fi

echo "INSTALLING PYTHON PACKAGES..."
virtualenv venv -p python3
source venv/bin/activate
pip install -r requirements.txt

echo "FINISHED INSTALLING LOCAL DEPENDENCIES"
