#!/bin/bash
#
#  Install and set up required software
#
echo "INSTALLING PYTHON PACKAGES..."
pip install -r requirements.txt
echo "DOWNLOADING E00CONV..."
mkdir bin
cd bin
E00COMPR="e00compr-1.0.1"
curl -OL http://avce00.maptools.org/dl/$E00COMPR.tar.gz
tar xzvf $E00COMPR.tar.gz
ln -s $E00COMPR e00compr
cd $E00COMPR
echo "MAKING E00CONV..."
make
cd ../../
echo "DONE!"
