name: Underfoot Setup
description: Checks out the Underfoot repo and sets up tools and dependencies
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo add-apt-repository ppa:ubuntugis/ppa
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gdal-bin \
          libgdal-dev \
          osmosis \
          python3-gdal \
          python3.8 \
          python3.8-dev \
          sqlite3 \
          unzip \
          zip

    - name: Install Python and other dependencies
      run: python setup.py
