name: Build all packs

on:
  push:
    # Reprocess all packs if anything related to source processing changes.
    # TODO come up with a better way to exclude sources/util/__init__.py
    paths:
      - sources/util/c*
      - sources/util/m*
      - sources/util/p*
      - sources/util/r*
      - sources/util/t*
      - sources/util/u*
      - sources/util/w*
    branches: main
  workflow_dispatch:

jobs:
  skip-duplicates:
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}

  # https://code.dblock.org/2021/09/03/generating-task-matrix-by-looping-over-repo-files-with-github-actions.html
  list-packs:
    needs: skip-duplicates
    name: List packs
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "matrix=$(ls packs/*.json | xargs -I'{}' basename {} .json | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build-packs:
    name: Build packs
    needs: list-packs
    strategy:
      fail-fast: false
      matrix:
        pack: ${{ fromJson(needs.list-packs.outputs.matrix) }}
    uses: kueda/underfoot/.github/workflows/build-pack.yml@main
    with:
      pack: ${{ matrix.pack }}
    secrets: inherit
