name: Build changed packs

on:
  push:
    paths: packs/*.json
    branches: gh-actions

jobs:
  list-changed-packs:
    name: List changed packs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Detect changed pack definitions
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: gh-actions
          list-files: shell
          filters: |
            changed:
              - added|modified: 'packs/*.json'

      # Convert paths into a list of pack IDs
      - id: set-matrix
        # Run basename on the list of changed files then convert the list to
        # JSON
        run: |
          echo "matrix=$(basename -s .json ${{ steps.filter.outputs.changed_files }}) | | jq -R -s -c 'split("\n")[:-1]') >> $GITHUB_OUTPUT"

  build-packs:
    name: Build packs
    needs: list-changed-packs
    strategy:
      fail-fast: false
      matrix:
        pack: ${{ fromJson(needs.list-changed-packs.outputs.matrix) }}
    uses: kueda/underfoot/.github/workflows/build-pack.yml@gh-actions
    with:
      pack: ${{ matrix.pack }}
    secrets: inherit
