name: Build Underfoot packs

on: workflow_dispatch

jobs:
  # https://code.dblock.org/2021/09/03/generating-task-matrix-by-looping-over-repo-files-with-github-actions.html
  list-packs:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls packs/us-ca-oak*.json | xargs -I'{}' basename {} .json | jq -R -s -c 'split("\n")[:-1]')"

  build:
    needs: list-packs
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgis/postgis:12-2.5
        env:
          POSTGRES_USER: underfoot
          POSTGRES_PASSWORD: underfoot
          POSTGRES_DB: underfoot
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        packs: ${{ fromJson(needs.list-packs.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install -y build-essential git virtualenv python3.8 python3.8-dev python3-gdal gdal-bin libgdal-dev unzip osmosis sqlite3

      - name: Set up Python dependencies
        run: python setup.py

      - name: Build pack
        run: python packs.py ${{ matrix.packs }} --s3-bucket-url https://static.underfoot.rocks
        env:
          PGHOST: 0.0.0.0
          PGUSER: underfoot
          PGPASSWORD: underfoot
