name: Build changed packs

on:
  push:
    paths: packs/*.json
    branches: gh-actions

jobs:
  list-changed-packs:
    name: List changed packs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Detect changed pack definitions
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: gh-actions
          list_files: json
          filters: |
            changed_packs:
              - added|modified: 'packs/*.json'

      # Convert paths into a list of pack IDs
      - id: set-matrix
        # jq converts the JSON array in steps.filter.outputs.changes to lines
        # fed to basename via xargs, resulting in just the basenames of all
        # the changed paths
        run: |
          echo '${{ steps.filter.outputs.changed_packs_files }}' && echo "matrix=$(jq -r '.[]' <<< '${{ steps.filter.outputs.changes }}' | xargs -I'{}' basename {} .json  )" >> $GITHUB_OUTPUT

  build-packs:
    name: Build packs
    needs: list-changed-packs
    strategy:
      fail-fast: false
      matrix:
        pack: ${{ fromJson(needs.list-changed-packs.outputs.matrix) }}
    uses: kueda/underfoot/.github/workflows/build-pack.yml@gh-actions
    with:
      pack: ${{ matrix.pack }}
    secrets: inherit
